// src/components/CalendarHeader.tsx
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";

interface CalendarHeaderProps {
  currentDate: Date;
  onPrevMonth: () => void;
  onNextMonth: () => void;
}

const CalendarHeader = ({ currentDate, onPrevMonth, onNextMonth }: CalendarHeaderProps) => {
  return (
    <div className="flex items-center justify-between px-4 py-2">
      <Button
        variant="outline"
        size="icon"
        onClick={onPrevMonth}
        className="h-8 w-8"
      >
        <ChevronLeft className="h-4 w-4" />
      </Button>
      <h2 className="text-lg font-semibold">
        {format(currentDate, "MMMM yyyy")}
      </h2>
      <Button
        variant="outline"
        size="icon"
        onClick={onNextMonth}
        className="h-8 w-8"
      >
        <ChevronRight className="h-4 w-4" />
      </Button>
    </div>
  );
};

export default CalendarHeader;

// src/components/CalendarHeader.vue
<template>
  <div class="flex items-center justify-between px-4 py-2">
    <button
      class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-8 w-8"
      @click="$emit('prev-month')"
    >
      <ChevronLeft class="h-4 w-4" />
    </button>
    <h2 class="text-lg font-semibold">
      {{ format(currentDate, 'MMMM yyyy') }}
    </h2>
    <button
      class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-8 w-8"
      @click="$emit('next-month')"
    >
      <ChevronRight class="h-4 w-4" />
    </button>
  </div>
</template>

<script setup lang="ts">
import { format } from 'date-fns';
import { ChevronLeft, ChevronRight } from 'lucide-vue-next';

defineProps<{
  currentDate: Date;
}>();

defineEmits(['prev-month', 'next-month']);
</script>
